### ISSUE TITLE
Issue with App Crashing 

### ISSUE THREAD

**Issue by Jeffchiucp** [jorgeavelar98/Take-Me-Home#4]
Per Use testing, there is an issue with App frozen when the player UFO contacts with object. 
Please resolve the App crashing. @jorgeavelar98

**Comment by jorgeavelar98** [comment]
thanks, I am looking into it.

**Comment by Jeffchiucp** [comment]
Confirmed that App crashes when contacts with player UFO. Please fix the bug

**Comment by Jeffchiucp** [comment]
Please document the error message when crashes

**Comment by jorgeavelar98** [comment]
This is the message I am getting when the app crashes.

**2016-08-02 15:21:47.506 Take Me Home[4765:563478] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Attemped to add a SKNode which already has a parent: <SKAudioNode> name:'(null)' position:{0, 0} scale:{1.00, 1.00} accumulatedFrame:{{0, 0}, {0, 0}}'
**\* First throw call stack:
(0x25be791b 0x25382e17 0x25be7861 0x31eb86ff 0x31eb85b7 0x11d8d4 0x122620 0x1228f8 0x2a04d959 0x2a04b9b5 0x31e81ac9 0x31ea52bd 0x31ea19f5 0x31ea0f07 0x31ea2e5b 0x31ed54a7 0x45a905 0x28242a1b 0x28242867 0x2792950b 0x25e38759 0x25b9637d 0x25baa5b3 0x25ba9cc7 0x25ba80d9 0x25af7229 0x25af7015 0x270e7ac9 0x2a1c9189 0x130920 0x2579f873)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)**

**Comment by Jeffchiucp** [comment]
user testing requested
